name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: thebus_test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5
      - name: Setup Go 1.24
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"
      - run: go version
      - name: go fmt (check diff)
        run: |
            make fmt
            git diff --exit-code

      - name: go vet
        run: make vet

      - name: Test (race)
        run: make test-race
